// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SampleLMS.Data.Migrations
{
    [DbContext(typeof(CourseDbContext))]
    [Migration("20231102092335_UpdatingModels")]
    partial class UpdatingModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseCategory", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CourseCategory");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            CourseId = 1,
                            CategoryId = 2
                        },
                        new
                        {
                            CourseId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            CourseId = 2,
                            CategoryId = 2
                        },
                        new
                        {
                            CourseId = 2,
                            CategoryId = 3
                        });
                });

            modelBuilder.Entity("CourseModule", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "ModuleId");

                    b.HasIndex("ModuleId");

                    b.ToTable("CourseModule");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            ModuleId = 1
                        },
                        new
                        {
                            CourseId = 1,
                            ModuleId = 2
                        },
                        new
                        {
                            CourseId = 2,
                            ModuleId = 1
                        },
                        new
                        {
                            CourseId = 2,
                            ModuleId = 2
                        },
                        new
                        {
                            CourseId = 2,
                            ModuleId = 3
                        });
                });

            modelBuilder.Entity("SampleLMS.Models.DomainModels.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 3,
                            Name = "Containerization"
                        },
                        new
                        {
                            CategoryId = 1,
                            Name = "Cloud"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "DevOps"
                        });
                });

            modelBuilder.Entity("SampleLMS.Models.DomainModels.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("Duration")
                        .IsRequired()
                        .HasColumnType("time");

                    b.Property<string>("FeaturedImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Heading")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlHandle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Author = "",
                            Content = "aaaaaaaaaaaabbbbbbbccccccccc",
                            Description = "Docker is a containerization tool, used by all kinds of engineers.",
                            Duration = new TimeSpan(0, 2, 30, 0, 0),
                            FeaturedImageUrl = "",
                            Heading = "Docker",
                            Title = "Docker101",
                            UrlHandle = ""
                        },
                        new
                        {
                            CourseId = 2,
                            Author = "",
                            Content = "",
                            Description = "Kubernetes is a container orchestration tool",
                            Duration = new TimeSpan(0, 5, 30, 0, 0),
                            FeaturedImageUrl = "",
                            Heading = "",
                            Title = "Kubernetes",
                            UrlHandle = ""
                        });
                });

            modelBuilder.Entity("SampleLMS.Models.DomainModels.Module", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleId"));

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModuleId");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            ModuleId = 1,
                            ContentType = "",
                            ModuleName = "Containers"
                        },
                        new
                        {
                            ModuleId = 3,
                            ContentType = "",
                            ModuleName = "Basic Docker Commands"
                        },
                        new
                        {
                            ModuleId = 2,
                            ContentType = "",
                            ModuleName = "K8s Introductions"
                        });
                });

            modelBuilder.Entity("CourseCategory", b =>
                {
                    b.HasOne("SampleLMS.Models.DomainModels.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SampleLMS.Models.DomainModels.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseModule", b =>
                {
                    b.HasOne("SampleLMS.Models.DomainModels.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SampleLMS.Models.DomainModels.Module", null)
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
